name: Build and Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
        env:
          CI: false

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy using lftp
        run: |
          lftp -c "
          open $FTP_HOST
          user $FTP_USERNAME $FTP_PASSWORD
          mirror -R build /www
          bye
          "
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
